### ISSUE TITLE
Maximum weight for steps

### ISSUE THREAD

**Issue by Phoenixxx3** [Damian-AU/DSx#10]
Every time I set a maximum weight in one step of a profile, this maximum is also applied to all following steps. It happens to me on my test app on windows and also on my machine. I did report this already to John, but we found out, that it only happens on the DSx skin. Here is the issue: [https://github.com/decentespresso/de1app/issues/241](https://github.com/decentespresso/de1app/issues/241)

Steps to replicate this:

1. Dowload a profile from the visualizer. I used this one: [https://visualizer.coffee/api/shots/a1e3458a-7007-44ff-bf4e-ed1a74691bb6/profile](https://visualizer.coffee/api/shots/a1e3458a-7007-44ff-bf4e-ed1a74691bb6/profile)
2. Copy the profile in the profile folder.
3. Start the app.
4. Go to profile selection, select the profile, go to advanced profile settings.
5. Select a step (e.g. step 4) and set the maximium weight to 1.0
6. Click okay.
7. Repeat 4 (go to the advance setting of the profile).
All following steps will have a weight limit of 1.0

**Comment by Damian-AU** [comment]
Resolved in v5.03
